name: magic_workouts
description: "Technical challenge for Magic Engineering"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.4
  go_router: ^14.2.8
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
